name: note_firebase
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  
  mobx: ^0.4.0+1
  firebase_admob: ^0.9.0+10
  cached_network_image: ^2.0.0
  sliding_up_panel: ^0.3.6
  simple_animations: ^1.3.4
  provider: ^4.0.1
  smooth_star_rating: ^1.0.4+2
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.0+1
  carousel_pro: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  mobx_codegen: ^0.4.0+1

flutter:
  uses-material-design: true
  
  assets:
   - assets/images/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
    - family: Flaticon
      fonts:
        - asset: assets/fonts/Flaticon.ttf